config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'dashboard', to: 'projects#index'
  get 'projects/new', to: 'projects#new'
  post 'projects', to: 'projects#create'
  delete 'projects/:id', to: 'projects#destroy', as: 'destroy_project'
  root 'projects#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, presence:true
  validates :description, presence:true
  validates :status, presence:true
  
  enum status: [:proposal, :progress, :finished]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
    if params[:status] and params[:status] != 'all'
      @projects = @projects.where(status:params[:status])
    end
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to dashboard_path
    else
      render 'new'
    end
  end

  def destroy
    @project = Project.find(params[:id])
    if @project.destroy
      redirect_to dashboard_path
    end
  end

  private
  #Strong params
  def project_params
    params.require(:project).permit(:name, :description, :started_at, :ended_at, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectManagment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS 4.6.0 VERSION-->  
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-info">
    <a class="navbar-brand" href="#">Project Managment</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <%= link_to('Inicio',  root_path, class: 'nav-link') %>
        <%= link_to('Dashboard',  projects_new_path, class: 'nav-link') %>
        
      </div>
    </div>
  </nav>
    
  <div class="container my-5 py-5">
    <%= yield %>
  </div>

  <footer class="container-fluid text-white bg-dark mt-5">
    <div class="container icons d-flex justify-content-between align-items-center pt-3">
      <h4>Project Managment</h4>
        <ul class="footer-icons list-style-none text-white text-decoration-none">
            <li class="d-inline ">
                <a href="https://www.github.com"><i class="fab fa-github-square fa-2x pl-2" style="color:#ffffff"></i></a>
            </li>
            <li class="d-inline">
              <a href="https://www.linkedin.com"><i class="fab fa-linkedin fa-2x pl-2" style="color:#ffffff"></i></a>
            </li>
            <li class="d-inline">
                <a href="https://www.twitter.com"><i class="fab fa-twitter-square fa-2x pl-2" style="color:#ffffff"></i></a>
            </li>
            <li class="d-inline">
              <a href="https://www.facebook.com"><i class="fab fa-facebook-square fa-2x pl-2" style="color:#ffffff"></i></a>
            </li>
          </ul>
        </div>
        <p class="footer-rights text-center pb-3 mb-0">All Rights Reserved 2021. San José, Costa Rica</p>
  </footer>
       <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
  </body>
</html>

app/views/projects/index.html.erb
<div class="container text-center">
<h1>Projects Managment</h1>
<p>Crea un nuevo proyecto</p>

<%= link_to 'Crear Proyecto', projects_new_path, class: 'btn btn-info mb-5'%>
</div>


<%= form_with url: "/dashboard", method: :get, class: "form-inline" do |form| %>
 <div class="form-group mx-sm-3 mb-2">
  <%= form.label :query, "Filtrar proyectos: " %>
   <%= form.select :status, [["Todos", :all], ["Propuesta", :proposal], ["Progreso", :progress], ["Terminado", :finished]], {selected: params[:status]}, class:'form-control' %>
   </div>
  <%= form.submit "Buscar", class: 'btn btn-success mb-2' %>
<% end %>
<br>


<table class="table my-5">
  <thead>
    <tr>
      <th scope="col">Nombre</th>
      <th scope="col">Descripción</th>
      <th scope="col">Comenzado</th>
      <th scope="col">Terminado</th>
      <th scope="col">Estado</th>
      <th scope="col">Eliminar</th>
    </tr>
  </thead>
  <tbody>
    <tr>
    <% @projects.each do |project|%>
      <th><%= project.name %></th>
      <td><%= project.description %></td>
      <td><%= project.started_at %></td>
      <td><%= project.ended_at %></td>
      <td><%= project.status %></td>
      <td><%= link_to 'Eliminar', destroy_project_path(project), method: :delete %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/projects/new.html.erb
<h1 class="text-info">Formulario de proyectos</h1>
<% if @project.errors.any? %>
        <div id="error_explanation">
            <h3>
                <%= pluralize(@project.errors.count, "error") %> impiden guardar este post:</h3>
                <ul>
                <% @project.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>


<%= form_with model: @project do |form| %>
  <%= form.text_field :name, class:'form-control', placeholder: 'Nombre' %>
  <%= form.text_area :description, size: "60x10",class:'form-control', placeholder: 'Descripción' %>
  <%= form.date_field :started_at, class:'form-control' %>
  <%= form.date_field :ended_at, class:'form-control' %>
  <%= form.select :status, [["Propuesta", :proposal], ["Progreso", :progress], ["Terminado", :finished]],{}, class:'form-control' %>
  <br>
  <%= form.submit 'Enviar', class: 'btn btn-info' %>
<% end %>